<a href="https://colab.research.google.com/github/wiv33/A-Learning-python/blob/master/machine-learning/_000_hello_machine/_000_basic/_003_cuk_edu/_004_3_text_processing/_003_en_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, Flatten, Input, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
import numpy as np

In [5]:
docs = ['안 녕!',
        '잘했어!',
        '잘 자, 오늘 고생했어',
        '일 잘하는데?',
        '훌륭해',
        '약해',
        '노력 좀 해!',
        '별로다',
        '일을 너무 못 해',
        '잘할 수 있었잖아.']

labels = np.array([1,1,1,1,1,0,0,0,0,0])  # 긍정과 부정

In [6]:
# one hot vector
encoded_docs = [one_hot(doc, 50) for doc in docs]
encoded_docs

[[40, 26],
 [36],
 [15, 40, 9, 1],
 [25, 49],
 [7],
 [49],
 [6, 42, 20],
 [13],
 [20, 34, 41, 20],
 [34, 41, 34]]

In [8]:
# padding zero to one hot vector
padded_docs = pad_sequences(encoded_docs, maxlen=6, padding='post')

In [46]:
# model
import tensorflow.keras.backend as K
K.clear_session()

inputs = Input(shape=6)
layer = Embedding(input_dim=50, output_dim=8)(inputs)
layer = Flatten()(layer)
layer = Dense(1, activation='sigmoid')(layer)

model = Model(inputs, layer)

In [47]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [48]:
model.fit(x=padded_docs,
          y=labels,
          epochs=20,
          verbose=1)

Epoch 1/20
1/1 [==============================] - 1s 527ms/step - loss: 0.7014 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6999 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6985 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6971 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6943 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6929 - accuracy: 0.5000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6915 - accuracy: 0.5000
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6901 - accuracy: 0.5000
Epoch 10/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6887 - accuracy: 0.6000
Epoch 11/20
1/1 [==================

In [49]:
model.predict(padded_docs)

array([[0.5136125 ],
       [0.50698096],
       [0.5113176 ],
       [0.51299584],
       [0.51410687],
       [0.50622594],
       [0.48392665],
       [0.5012793 ],
       [0.47529897],
       [0.49258953]], dtype=float32)

In [37]:
model.layers[1].get_weights()[0]

array([[-0.01885519, -0.01091791, -0.03616605, -0.02317302, -0.04351425,
         0.03969439,  0.02844207,  0.04189774],
       [-0.01251173,  0.01534185,  0.03996464, -0.01551222, -0.02925817,
         0.03462544, -0.00736972, -0.02151651],
       [ 0.01036209,  0.00282185, -0.00072233,  0.01340958, -0.01509308,
         0.04946368,  0.0417848 ,  0.04892895],
       [-0.04015672, -0.03305737, -0.03740739,  0.03161499, -0.01644246,
        -0.03841694, -0.03615393,  0.01298783],
       [ 0.02190259, -0.03464351,  0.02711003, -0.03480168,  0.01968309,
        -0.046192  , -0.00241842, -0.03006525],
       [ 0.02427432, -0.0189677 , -0.02822081, -0.00523179, -0.00440508,
        -0.04198921,  0.03577704, -0.00240671],
       [-0.02335697,  0.02970469, -0.00662454,  0.00427003, -0.03219987,
        -0.01933762,  0.02426061,  0.00541779],
       [ 0.00564641,  0.03831062, -0.01629349,  0.01383264,  0.00746034,
        -0.02105585,  0.00320023, -0.02718769],
       [ 0.0374694 ,  0.04652485

In [32]:
sample_weights = np.arange(0.1, 1.1, 0.1)
sample_weights = np.array([sample_weights] * 4).T

# put sample_weights to embedding layer
model.layers[1].set_weights([sample_weights])
model.layers[1].get_weights()

[array([[0.1, 0.1, 0.1, 0.1],
        [0.2, 0.2, 0.2, 0.2],
        [0.3, 0.3, 0.3, 0.3],
        [0.4, 0.4, 0.4, 0.4],
        [0.5, 0.5, 0.5, 0.5],
        [0.6, 0.6, 0.6, 0.6],
        [0.7, 0.7, 0.7, 0.7],
        [0.8, 0.8, 0.8, 0.8],
        [0.9, 0.9, 0.9, 0.9],
        [1. , 1. , 1. , 1. ]], dtype=float32)]

In [35]:
sample_input = np.arange(1, 10, 1)
model.predict(sample_input)

array([[[0.2, 0.2, 0.2, 0.2]],

       [[0.3, 0.3, 0.3, 0.3]],

       [[0.4, 0.4, 0.4, 0.4]],

       [[0.5, 0.5, 0.5, 0.5]],

       [[0.6, 0.6, 0.6, 0.6]],

       [[0.7, 0.7, 0.7, 0.7]],

       [[0.8, 0.8, 0.8, 0.8]],

       [[0.9, 0.9, 0.9, 0.9]],

       [[1. , 1. , 1. , 1. ]]], dtype=float32)